const $=s=>document.querySelector(s), fmt=new Intl.NumberFormat('vi-VN',{maximumFractionDigits:0}), money=n=>`${fmt.format(Math.round(n||0))} đ`, pct=n=>`${new Intl.NumberFormat('vi-VN',{maximumFractionDigits:1}).format((n||0)*100)}%`;
const STORAGE_KEY='bonusCalculatorV2';
const defaults={period:'',revenue:0,region:'',storeCount:0,storesHit:0,revenuePct:0,profitPct:0,priceSupport:0,delegatedHours:0,delegatedRate:0,managers:[],leaders:[]};
let state=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')||structuredClone(defaults);
const K1={V01:1,V02:.97,V03:.93,V04:.9};
const K2={1:[1,1,1,1,1],2:[1.1,1.08,1.05,1.03,1],3:[1.4,1.3,1.15,1.1,1.03],4:[1.6,1.4,1.2,1.15,1.05],5:[1.6,1.5,1.3,1.2,1.1]};
const ids=['period','revenue','region','storeCount','storesHit','revenuePct','profitPct','priceSupport','delegatedHours','delegatedRate'];
function band(r){return r<3e9?0:r<5e9?1:r<12e9?2:r<16e9?3:4}function bandName(i){return ['Dưới 3 tỷ','Từ 3 - 5 tỷ','Từ 5 - 12 tỷ','Từ 12 - 16 tỷ','Trên 16 tỷ'][i]}
function calculate(){const r=+state.revenue||0,k1=K1[state.region]||0,k2=(K2[+state.storeCount]||[0,0,0,0,0])[band(r)],rev=Math.min(2,Math.max(.5,(+state.revenuePct/100>=1?1+(+state.revenuePct/100-1):1-2*(1-+state.revenuePct/100)))),p=+state.profitPct/100,profit=Math.min(2,Math.max(.5,p<=1.2?1+(p-1):1.2+(p-1.2)*5)),scale=Math.max(0,(+state.storesHit-1)*.05),cost=(+state.priceSupport||0)+(+state.delegatedHours||0)*(+state.delegatedRate||0),baseM=(1e7+r**.65*5.5)*k1*k2,baseL=r**.9*.016*k1*k2,mTarget=baseM*.6*rev+baseM*.4*profit+baseM*.4*scale,lTarget=baseL*.6*rev+baseL*.4*profit+baseL*.4*scale,mHours=sum(state.managers),lHours=sum(state.leaders),mFund=(mTarget-cost)*Math.min(mHours/180,1),lFund=lTarget*Math.min(lHours/180,1);return{r,k1,k2,band:bandName(band(r)),rev,profit,scale,cost,baseM,baseL,mTarget,lTarget,mHours,lHours,mFund,lFund}}
function sum(a){return a.reduce((s,x)=>s+(+x.hours||0),0)}
function renderPeople(type){const arr=type==='manager'?state.managers:state.leaders,box=$(`#${type}Rows`);box.innerHTML='';arr.forEach((p,i)=>{const row=document.createElement('div');row.className='person-row';row.innerHTML=`<input aria-label="Họ tên" value="${esc(p.name)}"><input aria-label="Giờ công" type="number" min="0" step="0.5" value="${p.hours}"><button class="remove" title="Xóa">×</button>`;const ins=row.querySelectorAll('input');ins[0].oninput=e=>{p.name=e.target.value;update()};ins[1].oninput=e=>{p.hours=+e.target.value||0;update()};row.querySelector('button').onclick=()=>{arr.splice(i,1);renderPeople(type);update()};box.append(row)})}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function resultRows(arr,total,fund){return arr.map(p=>{const share=total?(+p.hours||0)/total:0,bonus=(+p.hours||0)?fund*share:0;return `<tr><td>${esc(p.name||'—')}</td><td>${fmt.format(p.hours||0)}</td><td>${pct(share)}</td><td class="money">${money(bonus)}</td></tr>`}).join('')||'<tr><td colspan="4">Chưa có dữ liệu</td></tr>'}
function update(){ids.forEach(id=>{const el=$('#'+id);state[id]=el.type==='number'||el.tagName==='SELECT'&&id==='storeCount'?+el.value:el.value});state.storesHit=Math.min(+state.storeCount,Math.max(0,+state.storesHit));$('#storesHit').value=state.storesHit;const x=calculate();$('#managerFund').textContent=money(x.mFund);$('#leaderFund').textContent=money(x.lFund);$('#managerHours').textContent=`${fmt.format(x.mHours)} giờ công`;$('#leaderHours').textContent=`${fmt.format(x.lHours)} giờ công`;$('#revRate').textContent=pct(x.rev);$('#profitRate').textContent=pct(x.profit);$('#managerResults').innerHTML=resultRows(state.managers,x.mHours,x.mFund);$('#leaderResults').innerHTML=resultRows(state.leaders,x.lHours,x.lFund);const d=[['Hệ số vùng K1',x.k1],['Nhóm doanh thu',x.band],['Hệ số K2',x.k2],['Tỷ lệ thưởng quy mô',pct(x.scale)],['Chi phí siêu thị',money(x.cost)],['Thưởng chuẩn QL',money(x.baseM)],['Thưởng chuẩn TC',money(x.baseL)],['Quỹ Target QL trước chi phí',money(x.mTarget)],['Quỹ Target TC',money(x.lTarget)]];$('#details').innerHTML=d.map(([a,b])=>`<div class="detail"><span>${a}</span><b>${b}</b></div>`).join('');localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function init(){ids.forEach(id=>{$('#'+id).value=state[id];$('#'+id).addEventListener('input',update)});renderPeople('manager');renderPeople('leader');update()}
document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const type=b.dataset.add,arr=type==='manager'?state.managers:state.leaders;arr.push({name:'',hours:0});renderPeople(type);update()});
$('#resetBtn').onclick=()=>{if(confirm('Xóa toàn bộ dữ liệu đã nhập?')){state=structuredClone(defaults);localStorage.removeItem(STORAGE_KEY);ids.forEach(id=>$('#'+id).value=state[id]);renderPeople('manager');renderPeople('leader');update()}};$('#printBtn').onclick=()=>window.print();
$('#exportBtn').onclick=()=>{const x=calculate(),rows=[['Kỳ tính thưởng',state.period],['Quỹ QL Final',Math.round(x.mFund)],['Quỹ TC Final',Math.round(x.lFund)],[],['Loại','Họ tên','Giờ công','Tỷ trọng','Tiền thưởng']];state.managers.forEach(p=>rows.push(['Quản lý',p.name,p.hours,x.mHours?p.hours/x.mHours:0,Math.round(x.mHours?x.mFund*p.hours/x.mHours:0)]));state.leaders.forEach(p=>rows.push(['Trưởng ca',p.name,p.hours,x.lHours?p.hours/x.lHours:0,Math.round(x.lHours?x.lFund*p.hours/x.lHours:0)]));const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`thuong-${state.period.replaceAll('.','-')}.csv`;a.click();URL.revokeObjectURL(a.href)};
init();
