const $=s=>document.querySelector(s), fmt=new Intl.NumberFormat('vi-VN',{maximumFractionDigits:0}), money=n=>`${fmt.format(Math.round(n||0))} đ`, pct=n=>`${new Intl.NumberFormat('vi-VN',{maximumFractionDigits:1}).format((n||0)*100)}%`;
const STORAGE_KEY='bonusCalculatorV8';
const DELEGATED_RATE=2000;
const defaults={schemaVersion:9,revenue:0,region:'',storeCount:0,storesHit:0,revenuePct:0,profitPct:0,realtimeRevenuePct:0,realtimeProfitPct:0,currentMonth:new Date().getMonth()+1,useRealtimeEstimate:true,priceSupport:0,delegatedHours:0,managers:[],leaders:[]};
const savedState=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');
let state=savedState||structuredClone(defaults);
state={...structuredClone(defaults),...state};
// Nâng cấp dữ liệu từ phiên bản cũ: bật Realtime mặc định một lần nhưng vẫn giữ toàn bộ số liệu đã nhập.
if(savedState && !savedState.schemaVersion){state.useRealtimeEstimate=true;state.schemaVersion=9;}
const K1={V01:1,V02:.97,V03:.93,V04:.9};
const K2={1:[1,1,1,1,1],2:[1.1,1.08,1.05,1.03,1],3:[1.4,1.3,1.15,1.1,1.03],4:[1.6,1.4,1.2,1.15,1.05],5:[1.6,1.5,1.3,1.2,1.1]};
const ids=['revenue','region','storeCount','storesHit','revenuePct','profitPct','realtimeRevenuePct','realtimeProfitPct','currentMonth','useRealtimeEstimate','priceSupport','delegatedHours'];
const numericIds=new Set(['revenue','storeCount','storesHit','revenuePct','profitPct','realtimeRevenuePct','realtimeProfitPct','currentMonth','priceSupport','delegatedHours']);
const integerIds=new Set(['revenue','storesHit','priceSupport']);
const signedIds=new Set();
function parseNumber(v,allowNegative=false){const t=String(v??'').trim().replace(/\s/g,'');if(!t)return 0;const negative=allowNegative&&t.startsWith('-');const raw=negative?t.slice(1):t;const normalized=raw.includes(',')?raw.replace(/\./g,'').replace(',','.'):raw.replace(/\./g,'');const n=Number(normalized);if(!Number.isFinite(n))return 0;return negative?-Math.abs(n):Math.max(0,n)}
function formatInteger(v){return fmt.format(Math.round(Number(v)||0))}
function formatDecimal(v){const n=Number(v)||0;return new Intl.NumberFormat('vi-VN',{maximumFractionDigits:2}).format(n)}
function setupNumericInput(el,id,onChange){const integer=integerIds.has(id),signed=signedIds.has(id);el.addEventListener('focus',()=>{if(parseNumber(el.value,signed)===0)el.value='';requestAnimationFrame(()=>el.select())});el.addEventListener('input',()=>{if(integer){let negative=signed&&el.value.trim().startsWith('-');const digits=el.value.replace(/\D/g,'');el.value=digits?`${negative?'-':''}${fmt.format(Number(digits))}`:(negative?'-':'')}else{let value=el.value.replace(/[^0-9,.-]/g,'').replace('.',',');if(!signed)value=value.replace(/-/g,'');else value=(value.startsWith('-')?'-':'')+value.replace(/-/g,'');const first=value.indexOf(',');if(first>=0)value=value.slice(0,first+1)+value.slice(first+1).replace(/,/g,'');el.value=value}onChange()});el.addEventListener('blur',()=>{const n=parseNumber(el.value,signed);el.value=integer?formatInteger(n):formatDecimal(n);onChange()})}
function band(r){return r<3e9?0:r<5e9?1:r<12e9?2:r<16e9?3:4}function bandName(i){return ['Dưới 3 tỷ','Từ 3 - 5 tỷ','Từ 5 - 12 tỷ','Từ 12 - 16 tỷ','Trên 16 tỷ'][i]}
function calculate(){const r=+state.revenue||0,k1=K1[state.region]||0,k2=(K2[+state.storeCount]||[0,0,0,0,0])[band(r)],month=Math.min(12,Math.max(1,+state.currentMonth||1)),officialRevenue=(+state.revenuePct||0)/100,officialProfit=(+state.profitPct||0)/100,estimatedRevenue=((+state.revenuePct||0)*(month-1)+(+state.realtimeRevenuePct||0))/month/100,estimatedProfit=((+state.profitPct||0)*(month-1)+(+state.realtimeProfitPct||0))/month/100,revenueCompletion=state.useRealtimeEstimate?estimatedRevenue:officialRevenue,profitCompletion=state.useRealtimeEstimate?estimatedProfit:officialProfit,rev=Math.min(2,Math.max(.5,revenueCompletion>=1?1+(revenueCompletion-1):1-2*(1-revenueCompletion))),p=profitCompletion,profit=Math.min(2,Math.max(.5,p<=1.2?1+(p-1):1.2+(p-1.2)*5)),scale=Math.max(0,(+state.storesHit-1)*.05),cost=(+state.priceSupport||0)+(+state.delegatedHours||0)*DELEGATED_RATE,baseM=(1e7+r**.65*5.5)*k1*k2,baseL=r**.9*.016*k1*k2,mTarget=baseM*.6*rev+baseM*.4*profit+baseM*.4*scale,lTarget=baseL*.6*rev+baseL*.4*profit+baseL*.4*scale,mHours=sum(state.managers),lHours=sum(state.leaders),mFund=Math.max(0,(mTarget-cost)*Math.min(mHours/180,1)),lFund=lTarget*Math.min(lHours/180,1);return{r,k1,k2,band:bandName(band(r)),month,officialRevenue,officialProfit,estimatedRevenue,estimatedProfit,revenueCompletion,profitCompletion,rev,profit,scale,cost,baseM,baseL,mTarget,lTarget,mHours,lHours,mFund,lFund}}
function sum(a){return a.reduce((s,x)=>s+(+x.hours||0),0)}
function renderPeople(type){const arr=type==='manager'?state.managers:state.leaders,box=$(`#${type}Rows`),namePh=type==='manager'?'Tên Quản lý':'Tên Trưởng ca';box.innerHTML='';arr.forEach((p,i)=>{const row=document.createElement('div');row.className='person-row';row.innerHTML=`<input aria-label="Họ tên" placeholder="${namePh}" value="${esc(p.name)}"><input aria-label="Giờ công" placeholder="Giờ công" type="text" inputmode="decimal" value="${formatDecimal(p.hours)}" autocomplete="off"><button class="remove" title="Xóa">×</button>`;const ins=row.querySelectorAll('input');ins[0].oninput=e=>{p.name=e.target.value;update()};ins[1].addEventListener('focus',()=>{if(parseNumber(ins[1].value)===0)ins[1].value='';ins[1].select()});ins[1].addEventListener('input',e=>{let value=e.target.value.replace(/[^0-9,.]/g,'').replace('.',',');const first=value.indexOf(',');if(first>=0)value=value.slice(0,first+1)+value.slice(first+1).replace(/,/g,'');e.target.value=value;p.hours=parseNumber(value);update()});ins[1].addEventListener('blur',e=>{p.hours=parseNumber(e.target.value);e.target.value=formatDecimal(p.hours);update()});row.querySelector('button').onclick=()=>{arr.splice(i,1);renderPeople(type);update()};box.append(row)})}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function resultRows(arr,total,fund){return arr.map(p=>{const share=total?(+p.hours||0)/total:0,bonus=(+p.hours||0)?fund*share:0;return `<tr><td>${esc(p.name||'—')}</td><td>${new Intl.NumberFormat('vi-VN',{maximumFractionDigits:2}).format(p.hours||0)}</td><td>${pct(share)}</td><td class="money">${money(bonus)}</td></tr>`}).join('')||'<tr><td colspan="4">Chưa có dữ liệu</td></tr>'}
function realtimeStatus(value){const n=Number(value)||0;if(n>=100)return{label:'Đạt / vượt target',className:'status-good'};if(n>=95)return{label:'Gần đạt target',className:'status-warning'};return{label:'Chưa đạt target',className:'status-danger'}}
function renderRealtime(id,value){const el=$('#'+id);if(!el)return;const s=realtimeStatus(value);el.className=`realtime-status ${s.className}`;el.innerHTML=`<i aria-hidden="true"></i><span>${s.label}</span>`}
function update(){ids.forEach(id=>{const el=$('#'+id);state[id]=id==='useRealtimeEstimate'?el.checked:(numericIds.has(id)?parseNumber(el.value,signedIds.has(id)):el.value)});state.storesHit=Math.min(+state.storeCount,Math.max(0,+state.storesHit));const storesHit=$('#storesHit');if(document.activeElement!==storesHit)storesHit.value=formatInteger(state.storesHit);const x=calculate();$('#managerFund').textContent=money(x.mFund);$('#leaderFund').textContent=money(x.lFund);$('#managerHours').textContent=`${new Intl.NumberFormat('vi-VN',{maximumFractionDigits:2}).format(x.mHours)} giờ công`;$('#leaderHours').textContent=`${new Intl.NumberFormat('vi-VN',{maximumFractionDigits:2}).format(x.lHours)} giờ công`;$('#revRate').textContent=pct(x.rev);$('#profitRate').textContent=pct(x.profit);renderRealtime('realtimeRevenueStatus',state.realtimeRevenuePct);renderRealtime('realtimeProfitStatus',state.realtimeProfitPct);$('#estimatedRevenuePct').textContent=pct(x.estimatedRevenue);$('#estimatedProfitPct').textContent=pct(x.estimatedProfit);$('#calculationModeNote').textContent=state.useRealtimeEstimate?`Đang dùng lũy kế ước tính Realtime tháng ${x.month} để tính thưởng.`:'Đang dùng lũy kế chính thức TUVH để tính thưởng.';$('#managerResults').innerHTML=resultRows(state.managers,x.mHours,x.mFund);$('#leaderResults').innerHTML=resultRows(state.leaders,x.lHours,x.lFund);const d=[['Hệ số vùng K1',x.k1],['Nhóm doanh thu',x.band],['Hệ số K2',x.k2],['Chế độ tính thưởng',state.useRealtimeEstimate?'LK ước tính Realtime':'LK chính thức TUVH'],['% HT Target doanh thu đang dùng',pct(x.revenueCompletion)],['% HT Target LNTT đang dùng',pct(x.profitCompletion)],['LK doanh thu chính thức',pct(x.officialRevenue)],['LK LNTT chính thức',pct(x.officialProfit)],['LK doanh thu ước tính',pct(x.estimatedRevenue)],['LK LNTT ước tính',pct(x.estimatedProfit)],['Realtime doanh thu tháng',`${formatDecimal(state.realtimeRevenuePct)}%`],['Realtime LNTT tháng',`${formatDecimal(state.realtimeProfitPct)}%`],['Tỷ lệ thưởng quy mô',pct(x.scale)],['Chi phí siêu thị',money(x.cost)],['Thưởng chuẩn QL',money(x.baseM)],['Thưởng chuẩn TC',money(x.baseL)],['Quỹ Target QL trước chi phí',money(x.mTarget)],['Quỹ Target TC',money(x.lTarget)]];$('#details').innerHTML=d.map(([a,b])=>`<div class="detail"><span>${a}</span><b>${b}</b></div>`).join('');localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function init(){ids.forEach(id=>{const el=$('#'+id);if(id==='useRealtimeEstimate')el.checked=!!state[id];else if(integerIds.has(id))el.value=formatInteger(state[id]);else if(numericIds.has(id)&&id!=='storeCount'&&id!=='currentMonth')el.value=formatDecimal(state[id]);else el.value=state[id];if(numericIds.has(id)&&el.tagName!=='SELECT')setupNumericInput(el,id,update);else el.addEventListener('input',update)});if(!state.managers.length)state.managers.push({name:'',hours:0});if(!state.leaders.length)state.leaders.push({name:'',hours:0});renderPeople('manager');renderPeople('leader');update()}
document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const type=b.dataset.add,arr=type==='manager'?state.managers:state.leaders;arr.push({name:'',hours:0});renderPeople(type);update()});
$('#resetBtn').onclick=()=>{if(confirm('Xóa toàn bộ dữ liệu đã nhập?')){state=structuredClone(defaults);localStorage.removeItem(STORAGE_KEY);ids.forEach(id=>{const el=$('#'+id);if(id==='useRealtimeEstimate')el.checked=true;else if(integerIds.has(id))el.value='0';else if(numericIds.has(id)&&id!=='storeCount'&&id!=='currentMonth')el.value='0';else el.value=state[id]});state.managers.push({name:'',hours:0});state.leaders.push({name:'',hours:0});renderPeople('manager');renderPeople('leader');update()}};$('#printBtn').onclick=()=>window.print();
$('#exportBtn').onclick=()=>{const x=calculate(),rows=[['Chế độ tính thưởng',state.useRealtimeEstimate?'LK ước tính Realtime':'LK chính thức TUVH'],['Tháng hiện tại',x.month],['% HT Target Doanh thu LK chính thức',x.officialRevenue],['% HT Target LNTT LK chính thức',x.officialProfit],['% HT Target Doanh thu tháng (Realtime)',state.realtimeRevenuePct/100],['% HT Target LNTT tháng (Realtime)',state.realtimeProfitPct/100],['% HT Target Doanh thu LK ước tính',x.estimatedRevenue],['% HT Target LNTT LK ước tính',x.estimatedProfit],['% HT Target Doanh thu đang dùng',x.revenueCompletion],['% HT Target LNTT đang dùng',x.profitCompletion],['Quỹ QL Final',Math.round(x.mFund)],['Quỹ TC Final',Math.round(x.lFund)],[],['Loại','Họ tên','Giờ công','Tỷ trọng','Tiền thưởng']];state.managers.forEach(p=>rows.push(['Quản lý',p.name,p.hours,x.mHours?p.hours/x.mHours:0,Math.round(x.mHours?x.mFund*p.hours/x.mHours:0)]));state.leaders.forEach(p=>rows.push(['Trưởng ca',p.name,p.hours,x.lHours?p.hours/x.lHours:0,Math.round(x.lHours?x.lFund*p.hours/x.lHours:0)]));const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='tinh-thuong.csv';a.click();URL.revokeObjectURL(a.href)};
init();
